import { createAdminSupabaseClient } from "@/lib/supabase/service";
import { unstable_noStore as noStore } from 'next/cache';
import { deriveCompany, deriveCompanySlug } from '@/lib/scanner/shared';

export { deriveCompany, deriveCompanySlug };

function attachGraph(match: any, nodes: any[] | null, edges: any[] | null) {
  match.checks = match.checks || {};
  match.checks.graph = {
    nodes: (nodes || []).map((n: any) => ({
      id: n.node_id,
      label: n.title,
      type: n.type,
      url: n.source_url,
      isExpensive: (n.properties?.wordCount ?? 0) > 1500,
      weight: 0,
      synthetic: n.synthetic === true || n.properties?.synthetic === true || n.properties?.autoGenerated === true,
      confidence: n.confidence,
      evidence: n.evidence || n.properties?.evidence,
      metadata: n.properties || {},
    })),
    edges: (edges || []).map((e: any) => ({
      source: e.from_id,
      target: e.to_id,
      type: e.relation,
    })),
    metrics: match.checks.graph?.metrics || {
      islands: 0,
      deadEnds: 0,
      missingBridges: 0,
      adjacencyScore: 0,
      continuityScore: 0,
    },
  };
  return match;
}

export async function getScanBySlug(slug: string) {
  if (!slug || slug.includes('.')) {
    return null;
  }

  let companyName = slug.toLowerCase();
  if (companyName.endsWith('-scan')) {
    companyName = companyName.slice(0, -5);
  }

  noStore();
  const supabase = createAdminSupabaseClient();

  // Fast path: company_slug column (Phase 5)
  const { data: bySlug, error: slugErr } = await supabase
    .from('public_scans')
    .select('*')
    .eq('company_slug', companyName)
    .order('created_at', { ascending: false })
    .limit(5);

  let match: any = null;

  if (!slugErr && bySlug && bySlug.length > 0) {
    // Prefer is_latest when present
    match = bySlug.find((r: any) => r.is_latest === true) || bySlug[0];
  } else {
    // Fallback: latest by derived company (legacy rows without company_slug)
    // Bounded fetch instead of full table when possible
    const { data, error } = await supabase
      .from('public_scans')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(200);

    if (error) {
      console.error('getScanBySlug error:', error.message);
      return null;
    }
    if (!data || data.length === 0) return null;

    match = data.find((item: any) => {
      if (item.company_slug) return item.company_slug === companyName;
      return deriveCompany(item.url).toLowerCase() === companyName;
    });
  }

  if (!match) return null;

  const { data: nodes } = await supabase
    .from('scan_nodes')
    .select('*')
    .eq('scan_id', match.id);

  const { data: edges } = await supabase
    .from('scan_edges')
    .select('*')
    .eq('scan_id', match.id);

  return attachGraph(match, nodes, edges);
}
