/**
 * Markdown report for CLI / shareable output (SPEC-09).
 */

import type { ScanResult } from './runScan';
import { scoreBandLabel } from '../shared/scoreBand';

export function formatScanMarkdown(result: ScanResult): string {
  const band = scoreBandLabel(result.score);
  const lines: string[] = [];

  lines.push(`# Agent Readiness Report`);
  lines.push('');
  lines.push(`**URL:** ${result.url}`);
  lines.push(`**Score:** ${result.score}/100 — ${band}`);
  lines.push(`**score_version:** \`${result.score_version}\``);
  lines.push(`**Duration:** ${result.duration_ms}ms`);
  lines.push(`**Framework:** ${result.framework}`);
  lines.push('');
  lines.push(`## Surfaces`);
  lines.push('');
  lines.push(`| Type | Status | Found | URL |`);
  lines.push(`| --- | --- | --- | --- |`);
  for (const s of result.surfaces) {
    if (s.status === 'skipped') continue;
    lines.push(
      `| ${s.type} | ${s.status} | ${s.found ? 'yes' : 'no'} | ${s.url.replace(/\|/g, '\\|')} |`
    );
  }
  lines.push('');

  lines.push(`## Dimensions`);
  lines.push('');
  for (const d of result.dimensions) {
    lines.push(`### ${d.name}: ${d.score}/${d.maxScore}`);
    lines.push(d.description);
    for (const o of d.observations) {
      lines.push(`- ${o}`);
    }
    lines.push('');
  }

  lines.push(`## Journeys (deterministic pathfinder)`);
  lines.push('');
  lines.push(
    `Completion: **${result.journeys.overallCompletionRate}%** · Avg hops: **${result.journeys.avgHopCount}**`
  );
  lines.push('');
  lines.push(`| Journey | Status | Hops | Pressure |`);
  lines.push(`| --- | --- | --- | --- |`);
  for (const t of result.journeys.traces) {
    lines.push(
      `| ${t.label} | ${t.success ? 'passed' : t.status} | ${t.hopCount} | ${t.hallucinationPressure} |`
    );
  }
  lines.push('');

  const fixes = result.journeys.traces
    .filter((t) => t.recommendedFix)
    .slice(0, 8);
  if (fixes.length) {
    lines.push(`## Recommended fixes`);
    lines.push('');
    for (const t of fixes) {
      lines.push(`### ${t.label}`);
      lines.push(t.recommendedFix || '');
      lines.push('');
    }
  }

  lines.push(`## Methodology`);
  lines.push('');
  lines.push(
    `See [ARS 1.0 methodology](../docs/methodology/ars-1.0.md) — deterministic, versioned scoring.`
  );
  lines.push('');
  lines.push(`---`);
  lines.push(`*Generated by Glintscanner*`);

  return lines.join('\n');
}
